### ISSUE TITLE
wiki 语句优化

### ISSUE THREAD

**Issue by quxiaolong1504** [douban/gobeansdb#22]
[wiki htree：结构，冲突处理，内存和速度优化](https://github.com/douban/gobeansdb/wiki/htree%EF%BC%9A%E7%BB%93%E6%9E%84%EF%BC%8C%E5%86%B2%E7%AA%81%E5%A4%84%E7%90%86%EF%BC%8C%E5%86%85%E5%AD%98%E5%92%8C%E9%80%9F%E5%BA%A6%E4%BC%98%E5%8C%96)

「为了减少 go 内存使用效率和 gc 的影响」 感觉有歧义。是不是可以改成：「为了减少受 go 内存使用效率和 gc 的影响」
@ariesdevil

**Comment by youngsofun** [comment]
改了下 @quxiaolong1504

**Comment by quxiaolong1504** [comment]
👍
