### ISSUE TITLE
如何同步？

### ISSUE THREAD

**Issue by jiangyunpeng** [douban/gobeansdb#38]
文档提到”同步脚本不断比较一个桶三副本 htree（每个桶一个 16 叉的内存 merkle tree）做同步“

 同步脚本有开源吗？

**Comment by youngsofun** [comment]
有，参考 https://github.com/douban/beansdbadmin/blob/master/beansdbadmin/core/sync.py
为了省内存这里用了较短的hash，所以同步脚本写的比较绕。
如果是 value 比较大的场景，gobeansdb 其实可以考虑用更长 hash，会简单很多。
